name: hexlet-ci-app

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: make setup
      - uses: make start
      - run: make test
      - run: make lint